### ISSUE TITLE
working directory is not created

### ISSUE THREAD

**Issue by tfjmp** [arthurscchan/ProvMark#3]
```
Starting stage 4...Generating benchmark
Traceback (most recent call last):
  File "/home/vagrant/tmp/ProvMark/processGraph/findSubgraph.py", line 21, in <module>
    os.chdir(workingDir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/tmp/ProvMark/working'
End of stage 4
```

Can be fixed by simply `mkdir working`

**Comment by jamescheney** [comment]
Is this still a problem?  I no longer encounter this when doing a fresh install with SPADE, and it looks like there is code in fullAutomation.py that creates working/ if it is not already present.  (git is particular about empty directories...)

**Comment by tfjmp** [comment]
This seem fixed. Although I have a new set of error see https://github.com/arthurscchan/ProvMark/issues/7
